### ISSUE TITLE
Licensing info on art needed

### ISSUE THREAD

**Issue by ExcaliburZero** [Rui914/mobtalker#4]
From what I can tell the artwork of the mobs used in the mod is from the Minecraft mod Mobtalker. However there is not any information on its licensing in this mod. In order to use the artwork, the artwork's use needs to follow the artwork's original license.

**Comment by Rui914** [comment]
I forgot!
I'm contacted the author (AT2).

**Comment by ExcaliburZero** [comment]
@Rui914 
Do you mean that you have contacted the artist, or that you are trying to contact the artist?

If you have permission from the artist to use the art, then you should add a note about that to the readme.

**Comment by Rui914** [comment]
It might take about one week to get permission.
I How should I do?

**Comment by Rui914** [comment]
License:
You can use content of the mob-girl pack in anyway you want(mirroring, modify, remake, port to other game...etc) **EXCEPT** for commercial purpose.

**Comment by ExcaliburZero** [comment]
>License:
You can use content of the mob-girl pack in anyway you want(mirroring, modify, remake, port to other game...etc) EXCEPT for commercial purpose.

Do you have a link to that license?

**Comment by Rui914** [comment]
https://mega.co.nz/#!wQESEIBK!uWGDQbkEeHq8UTzToy3VAJM_7w39wG9g0vs7huZ_W0w

**Comment by ExcaliburZero** [comment]
Okay, then we'll just need to add a note to the README that the artwork is licensed as such.

**Comment by Rui914** [comment]
Copy sic?
