### ISSUE TITLE
Adding more code documentation

### ISSUE THREAD

**Issue by ExcaliburZero** [Rui914/mobtalker#8]
Recently I've been looking through the code and I noticed that like most Minetest mods it does not have many comments to document what the different parts of it do.

Since I've been looking through the code to get a better understanding of it, do you want me to write up some documentation for it as I go through it?

Here is an example of some documentation for the init file:

```
mobtalker = {}
mobtalker.datadir = minetest.get_worldpath().."/mobtalker"

-- Run API
dofile(minetest.get_modpath("mobtalker").."/api.lua")
-- Run item registration
dofile(minetest.get_modpath("mobtalker").."/item.lua")

-- If the creeper mod is intalled, then run the creeper file
if minetest.get_modpath("creeper") then
	dofile(minetest.get_modpath("mobtalker").."/creeper.lua")
end
-- If the simple mobs mod is installed, then run the dungeon master file
if minetest.get_modpath("mobs") then
	--dofile(minetest.get_modpath("mobtalker").."/dm.lua")
end

-- Make a directory for modtalker, or read it if it already exists
mobtalker_mkdir()
```

**Comment by Rui914** [comment]
I added comments.

**Comment by ExcaliburZero** [comment]
Yep, the comments in the code look better now. If I find any sections that need more documentation, then I'll write up the documentation and make a pull request.
